### ISSUE TITLE
Request Feature

### ISSUE THREAD

**Issue by azrielbsi** [MhankBarBar/anime-game-stats#6]
Maybe you can add features in Genshin and Star Rail

Genshin:
- current resin
- Recovery Teapot Money
- Commission
and others as below
![image](https://github.com/MhankBarBar/anime-game-stats/assets/126305178/3def477a-4af1-4893-ab3d-0568b92864d0)

StarRail:
- Stamina Recovery Time
- Accepted Epedition Num
and others

**Comment by MhankBarBar** [comment]
i will add in next update
