### ISSUE TITLE
Cookie are not valid.

### ISSUE THREAD

**Issue by azrielbsi** [MhankBarBar/anime-game-stats#8]
Getting this error "genshin.errors.InvalidCookies: [-100] Cookies are not valid."

**Comment by MhankBarBar** [comment]
are you following [this instruction](https://github.com/MhankBarBar/anime-game-stats/blob/master/README_INFO.md#getting-started)? you need to add cookie (with json format) on github repository secret

**Comment by azrielbsi** [comment]
> are you following [this instruction](https://github.com/MhankBarBar/anime-game-stats/blob/master/README_INFO.md#getting-started)? you need to add cookie (with json format) on github repository secret

Yes, I have followed the instructions given but the results are still the same

**Comment by MhankBarBar** [comment]
the json key and value need to be update because hoyolab using new cookie (v2)

just update like this
```json
{"ltuid_v2": "...", "ltoken_v2": "...", "cookie_token_v2": "...", "account_id_v2": "...", "ltmid_v2": "..."}
```

**Comment by azrielbsi** [comment]
Thanks sir for the help, and it seems that the redeem code does not work

**Comment by MhankBarBar** [comment]
problem solved and redeem code things have been fixed, so i close this issue
